### ISSUE TITLE
32bit anywhere.?

### ISSUE THREAD

**Issue by deflesher** [Necrobot-Private/NecroBot#1352] opened 2017-03-24 00:21 UTC
If someone has a 32bit version of the latest NecroBot share it or can make one please do. My laptop is only 32x84

**Comment by Lord-Haji** [comment] 2017-03-24 03:49
@deflesher as on our 32 bit build. Some of the Antiviruses detects it is infected and we decided to close it for the time being.
 So we are researching on it, hope we will resolve these soon and 32 bit will again come up.
@deflesher do not make github issues if it is not a BUG REPORT or SUGGESTION :D 
limit these to our discord :D

**Closed by Lord-Haji** 2017-03-24 03:49 UTC
