### ISSUE TITLE
API-key problem?

### ISSUE THREAD

**Issue by Polytoxic75** [Necrobot-Private/NecroBot#1874] opened 2017-07-02 14:35 UTC
[16:32:17] () Configuration is up-to-date. Schema version: 27
[16:32:17] () Validating config.json...
[16:32:19] () Auth Configuration is up-to-date. Schema version: 27
[16:32:19] () Validating Auth.json...
[16:32:21] () The HashKey is invalid or has expired, please press any key to exit and correct you auth.json, 
 The Pogodev API key can be purchased at - https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

Always getting this error when starting bot. key should be valid until 11/07/17

**Comment by Furtif** [comment] 2017-07-02 15:13
hash server is unstable

**Comment by Polytoxic75** [comment] 2017-07-02 16:00
ok thx

**Comment by Matrixdk** [comment] 2017-07-02 16:31
i have the same 
[18:16:23] () Configuration is up-to-date. Schema version: 27
[18:16:23] () Validating config.json...
[18:16:23] () Auth Configuration is up-to-date. Schema version: 27
[18:16:23] () Validating Auth.json...
[18:16:23] () Console Layout is now 'Default'
[18:16:26] () The HashKey is invalid or has expired, please press any key to exit and correct you auth.json, 
 The Pogodev API key can be purchased at - https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by Adey123456789** [comment] 2017-07-03 05:35
same issue here for the past 24 hours at least

**Comment by Azuma57** [comment] 2017-07-03 06:10
same

**Comment by blackms** [comment] 2017-07-03 07:57
The problem is not related to Necrobot, but it's related to PogoDev.

**Comment by JingkunLi** [comment] 2017-07-03 12:16
still the same problem.
anyone know how to contact PogoDev?

**Comment by blackms** [comment] 2017-07-03 12:21
PogoDev Servers are still down, nothing related to Necrobot.

2017-07-03 14:16 GMT+02:00 Jingkun <notifications@github.com>:

**Comment by Adey123456789** [comment] 2017-07-03 18:04
i sent an email and the reply i got word for word was 

"the key is just fine, please use the specific support forum and discord channel for technical help, updates and advices"

though i have no idea what or where they are, thus why i emailed the support contact......hardly helpful at all

**Comment by night1245** [comment] 2017-07-04 03:13
so i guess it kinda working now when i enter my key in again run the bot it said it was wrong like always i checked the auth jons again and saw some shit like r/s in there so i back that out and save it run the bot and it started working again then after two min of working it then proceed to tell my has key is expired or invlaid i dont get what with all these issue but bossland api need to get their shit together or give us a free hash key or a or add more days on our keys since we couldnt bot for the days that the service was down.

**Comment by Adey123456789** [comment] 2017-07-04 06:38
ive replied to them again but still getting nothing

**Comment by night1245** [comment] 2017-07-04 06:59
well i got the bot to work but after like a min of running it will just quit for no reason due to the hash server but i just dont understand why it happen when the bot working perfectly find when it is running.

**Comment by TheWizard1328** [comment] 2017-07-04 07:22
@night1245 as mentioned above it's not the bot. It's the hash servers. Niantic pulled a fast one and overloaded the hash servers in order to shut them down or stop us from botting. Servers are partially up again but we will still get some outages till they are fully back online. And yes we've been told that there should be some compensation for missed time on hash keys once they are fully back online.

_Sent from my Samsung SM-N920W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by blackms** [comment] 2017-07-04 10:04
I'm going to close this since it's not related to necrobot code but hashing infrastructure.

**Closed** 2017-07-04 10:06 UTC
