### ISSUE TITLE
 ()Exception caught, writing LogBuffer - no .json

### ISSUE THREAD

**Issue by julro1990** [Necrobot-Private/NecroBot#1955] opened 2017-08-09 20:46 UTC
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.

--> yes, someone else had it, he was told to modify his auth.json. This doesn't apply to me, cause I don't even have one. 

2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
--> I don't have one

3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
--> I can't set it up cause it errors upon startup

4. Always confirm that your issue is reproducible, with the config you provide below.
--> none available

### Expected Behavior:
when I last started this bot, it took me step by step trough a setup process. I expected this.

### Actual Behavior:
Upon startup it says ()Exception caught, writing LogBuffer.. see scrennshot below.
![exception](https://user-images.githubusercontent.com/30878421/29142758-38649d70-7d53-11e7-8d18-440f7f7704cf.png)

### Your config.json:
--> none available

### Detailed Steps to Reproduce:
I downloaded the latest build, v1.0.0.187, started the console version and instead of leading me trough an **.json-creation it just errored. No .json, no logbuffer, nothing was created. OS: Win10

Version:
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): it won't even start

I'm really curious on how this bot works and how well it fares. Hope to get it up and running! Thanks for all replies! If you need any further infortmation pls don't hesitate to tell me what is necessary. I'm eager to provide it and learn interesting things for the future.

**Comment by Enielle** [comment] 2017-08-09 23:17
Having the exact same issue here.

**Comment by Furtif** [comment] 2017-08-09 23:40
Error auth.json

**Comment by Furtif** [comment] 2017-08-09 23:42
Fixed into https://github.com/Necrobot-Private/NecroBot/pull/1950 it is because assistant first config is bugged it is solved à this pr

**Comment by Enielle** [comment] 2017-08-10 08:51
Not understanding what you mean Furtif. Is that the fix or are you just telling me the cause of this issue.

**Comment by Enielle** [comment] 2017-08-10 22:45
Bump please. The bot isnt working at all :/

**Comment by blackuGT** [comment] 2017-08-11 06:44
This bug will be fixed in the new version... Look at other threads to fix it

**Closed** 2017-08-14 12:35 UTC
