### ISSUE TITLE
[Bug] Manual switch accounts

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#1477] opened 2017-04-13 08:15 UTC
### Expected Behavior:
Necrobot should have to switch to the selected account

### Actual Behavior:
Necrobot switches to another account (ie an account that I didn't selected).
In my example, my auth.json contains 5 accounts and I click to switch to the 2nd account.
![accounts](https://cloud.githubusercontent.com/assets/23528297/24996033/87c7535a-2031-11e7-8250-a9e613f046b7.png)
But Necrobot switches to the 5th account (the screen have been taken after the log, that's why the 5th account has its level in the screen but not in the log)
If I click one more time into the 2nd account, Necrobot will switch to the N°4. Then with the same click on the 2nd account, it will swtich to the N°3. And at the end, it will switch to the N°2.
After that, if I click on the account N°1, it will switch to the account N°4 (I can't success to determine the logic, I only think that I will need to click 4 times to go in the selected account N°1)

### (OPTIONAL) Your Log:
```
[09:49:31] (POKEMON) (Capturé) | (Normal) Fantominus Lvl: 1 CP: (11/1002) IV: 13.00% | Chance: 100% | dist 3359.80m | 60 PokéBall restante(s) | 1170XP | 3 Bonbons | lat: 44.847485 long: -0.540296 | Move1: LickFast Move2: SludgeBomb
[09:49:31] (INFO) Current level: 2. Skipped collecting level up rewards.
[09:50:32] (ATTENTION) Switch account requested by user
[09:50:32] (INFO) Account changed to XXX5.
[09:50:32] (INFO) XXX1 (Level: 2)			Runtime : 00:00:03:38
[09:50:32] (INFO) XXX2 (Level: ??)			Runtime : 00:00:00:00
[09:50:32] (INFO) XXX3 (Level: ??)			Runtime : 00:00:00:00
[09:50:32] (INFO) XXX4 (Level: ??)			Runtime : 00:00:00:00
[09:50:32] (INFO) XXX5 (Level: ??)			Runtime : 00:00:00:00
[09:50:32] (INFO) Connexion via Ptc
[09:50:51] (INFO) Connecté en tant que XXX5
```

### Detailed Steps to Reproduce:
Switch to another accounts (I don't know if this issue is reproduced only if there is 5 accounts, I will make test with differents accounts asap)

Version: 154
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): switch

**Comment by jjskuld** [comment] 2017-04-13 22:48
I'm not able to reproduce this.. is this reproducible on your end?

**Comment by macinmn** [comment] 2017-04-14 03:01
this happens for me too v153 and earlier regardless of number of accounts.    it just cycles, last, last-1, last-2, last-3, etc.  I'll check again when I get to DLing 155

**Comment by redking974** [comment] 2017-04-14 07:08
Yes, for me it's happened since several versions (I don't know exactly since what version too).
Do you have tried with 5 accounts or with a several number of accounts @jjskuld ?
If cycle that @macinmn is exact (last -> last - 1 -> ...) it follows the same cycle than if we let the bot switches (bot don't switch 1, 2, 3, ... but 1, last, last - 1).
But after one cycle, it seems to make something different because bot goes to account N°4 instead of account N°5 (the last of my list)

**Comment by 6Vampire6** [comment] 2017-04-14 11:08
For me the bot always switches to the account with the least runtime.
Additionally the runtime of the first bot is calculated wrong and goes up very fast so that it is never switched to.

**Comment by redking974** [comment] 2017-04-14 12:33
Hi @6Vampire6 the runtime issue have been "fixed" with last version (Necrobot reload the runtime at each starting).
For the bot, when I've several accounts with 0 time it goes to the last of the line (as @macinmn reported it) but I assume that if I choose an account manually the normal behaviour is to go to this account. This is why I add "manual" into the title of my issue.

**Comment by jjskuld** [comment] 2017-04-14 16:13
Yes, the runtime was increasing incorrectly prior to the last release but should be fixed now.

For me the manual switch is working for me, so please let me know if it is not for you.

The auto switch when time is 0 is a bug that should be fixed.

**Closed** 2017-04-14 16:23 UTC

**Comment by redking974** [comment] 2017-04-14 17:39
Hi @jjskuld I just try with 4 accounts (vs. 5 accounts in the first time) and I have the same issue (Necrobot doesn't switch to the selected account). Here my test :
4 accounts into my auth.json (called as 1, 2, 3, 4)
I delete accounts.db, so Necrobot begins with the 1st.
When I click into the 2nd account, Necrobot go to the N°4.
If I click again, it will go to the N°3
If I click a last time, it will bot to the N°2

With how many accounts have you tried ? Have you selected the 2nd account of the list or another account ?

**Comment by redking974** [comment] 2017-04-15 09:38
With 3 accounts, if the one that I want to select is in the first place, I will never success to go to the account N°1 : Necrobot will always choose the N°2 (if it's running on the N°3 or the N°3 (if it's running on the N°2) @jjskuld

**Comment by redking974** [comment] 2017-04-15 17:58
Ok, I think that it could be related to runtime issue. You fix it, but the fix will apply only on (re)load.
But in this case, I could never success to the first account (even if I click a dozen of times, it will never go to the first, at least manually) :
[19:50:50] (INFO) XXX (Level: 30)			Runtime : 00:00:38:09
[19:50:50] (INFO) XXX (Level: 30)			Runtime : 00:00:03:28
[19:50:50] (INFO) XXX (Level: 30)			Runtime : 00:00:02:47
[19:50:50] (INFO) XXX (Level: 30)			Runtime : 00:00:02:12
[19:50:50] (INFO) XXX (Level: 30)			Runtime : 00:00:05:02

The first account have the most higher runtime, so it could be the reason why Necrobot will never go to this account, even with a manual switch.
