### ISSUE TITLE
Scyther Evolution

### ISSUE THREAD

**Issue by dougrosa** [Necrobot-Private/NecroBot#1021] opened 2017-02-25 00:07 UTC
Scyther Evolution to Scizor is not working.

**Comment by samuraitruong** [comment] 2017-02-25 00:53
more specific?

**Comment by dougrosa** [comment] 2017-02-25 23:42
The bot check if your have candies OR the evolution item (metal coat). It should check if you have both em. The button to evolve was enabled and I hadn't the candies to evolve, just the metal coat.

**Comment by samuraitruong** [comment] 2017-03-02 11:24
you mean button enable when you don't have required item?

I not sure what is the issue is, but it should be fixed in - https://github.com/Necrobot-Private/NecroBot/pull/1134

**Closed by samuraitruong** 2017-03-02 11:24 UTC
