### ISSUE TITLE
Evolve not working

### ISSUE THREAD

**Issue by SoccerCore11** [Necrobot-Private/NecroBot#1104] opened 2017-02-28 22:57 UTC
### Expected Behavior:
Pokemon in 'PokemonEvolveFilter' should evolve

### Actual Behavior:
No Pokemon are evolving

### Your config.json:
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"EvolveKeptPokemonsAtStorageUsagePercentage": 0.0,
"EvolveKeptPokemonIfBagHasOverThisManyPokemon": 25,
"KeepPokemonsThatCanEvolve": true,
"EvolveOperator": "or",
"EvolveFavoritedOnly": false,
"EvolveMinIV": 1.0,
"EvolveMinCP": 1.0,
"EvolveMinLevel": 1.0

  "PokemonEvolveFilter": {
    "Caterpie": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": null,
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [ ],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    }
  },

### Detailed Steps to Reproduce:
I've enabled everything I can find to try to make evolves start happening, but they aren't. What do I need to change to make evolves start?

**Comment by ning1002** [comment] 2017-03-01 01:16
same problem here,,
I only caught pidgeys
I assume it doesn't evolve if there is no transfer
just guessing

**Comment by jjskuld** [comment] 2017-03-01 01:23
I'll take a look at this tonight.

**Comment by jjskuld** [comment] 2017-03-01 01:27
In the meantime do you have a log of evolve not working?

**Comment by jjskuld** [comment] 2017-03-01 01:29
@SoccerCore11 @ning1002 The only thing I see that might be causing this is that EvolveKeptPokemonsAtStorageUsagePercentage is set to 0.  Try setting it to 95 and see if that helps.

**Comment by SoccerCore11** [comment] 2017-03-01 01:30
Not sure what to provide from the log, there are no messages relating to
evolutions anywhere in the console. Will it still be helpful?

**Comment by SoccerCore11** [comment] 2017-03-01 01:31
I tried at both 95 and 0, no difference.

**Comment by jjskuld** [comment] 2017-03-01 01:31
@SoccerCore11 Ok, no messages at all.. Well that's helpful.  Ok, will take a look later tonight.

**Comment by hardknoxni69a** [comment] 2017-03-01 04:33
I know  setting up like this works for a fact it will save up all the pokemon that u can evolve and evolve at once. its really good to mass evolve with lucky egg get a couple hundred thousand in half hour enjoy let us know if you have more questions our discord is in the wiki guys
"EvolveAboveIvValue": 0.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 100.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 999,
    "KeepPokemonsThatCanEvolve": true,

    "EvolveOperator": "and",
    "EvolveFavoritedOnly": false,
    "EvolveMinIV": 0.0,
    "EvolveMinCP": 0.0,
    "EvolveMinLevel": 0.0

  "PokemonEvolveFilter": {
    "Caterpie": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Metapod",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0

**Comment by ning1002** [comment] 2017-03-01 09:34
As one of pidgey hunters, I have fixed this problem by touching bulk transfer options and transferMin options
I'd let
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 500,
    "KeepMinIvPercentage": 99.0,
    "KeepMinLvl": 28,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 0,

and 

    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 100,
    "BulkTransferSize": 10,

    "PokemonNotToTransfer": "pidgey"

It transferred all the pidgeottos and pidgeots and started evolution.
so I guess my hypothesis was kind of right that no transfer makes no evolution

**Comment by SoccerCore11** [comment] 2017-03-01 12:09
Yea, but I've been doing manual transfers. Evolutions shouldn't require the
transfer function to be enabled. This isn't documented anywhere, and I did
try asking on Discord first, but no one responded. I don't think that this
should be closed because it is still a bug.

**Comment by hardknoxni69a** [comment] 2017-03-01 15:35
You need to set up your evolutions like above and they will work for you the only reason this is closed because it's not a bug it's the way u have you config set up I have help a ton of people in our discord resolve this exact issue please look over the settings I uploaded and apply them to your config u can add more evolutions but the above layout will enable.evolutions the config file is ur friend study it and once u learn everything u won't believe how much easier everything is u won't even have to monitor ur bot anymore if u set everything up correctly we are here to help just because a bug isn't open doesn't mean we can't help you still fix it discord would.be fastest but u can reply here still

**Comment by SoccerCore11** [comment] 2017-03-01 16:09
I HAVE my config exactly as yours. I'm also very familiar with the program and the config file, having been using it for a few months, and probably have spent over 20 hours total tweaking it to get it to exactly my liking. Again, Discord was not helpful, I tried that with no response. Here is my exact config, as well as log file (redacted). I still argue that this is a bug.

`    "EvolveAboveIvValue": 0.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 100.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 999,
    "KeepPokemonsThatCanEvolve": true,`

`    "EvolveOperator": "and",
    "EvolveFavoritedOnly": false,
    "EvolveMinIV": 0.0,
    "EvolveMinCP": 0.0,
    "EvolveMinLevel": 0.0`

`  "PokemonEvolveFilter": {
    "Caterpie": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": null,
      "Operator": "and",
      "EvolveTo": "",
      "AffectToPokemons": [
        "weedle"
      ],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    }
  },`

`    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
  "PokemonsNotToTransfer": [],`

[NecroBot2-2017-03-01-10-43-14.txt](https://github.com/Necrobot-Private/NecroBot/files/811247/NecroBot2-2017-03-01-10-43-14.txt)

**Comment by jjskuld** [comment] 2017-03-01 17:27
This is

**Closed** 2017-03-01 17:45 UTC

**Comment by hardknoxni69a** [comment] 2017-03-01 19:27
Ahhh I see everyone didn't realize u made it not allow evolve unless there was a transfer because 99% of users transfer there junk
