### ISSUE TITLE
matters on priority with logs

### ISSUE THREAD

**Issue by ning1002** [Necrobot-Private/NecroBot#1175] opened 2017-03-05 18:16 UTC
### Expected Behavior:
priority with lower number should get caught often than 10

### Actual Behavior:
no difference or priority with higher number caught a lot

### Your config.json:
```
"SnipePokemonFilter": {
    "Pidgey": {
      "SnipeIV": 0,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 0,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Pidgeotto": {
      "SnipeIV": 80,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 10,
      "AutoSnipeCandy": 300,
      "Level": 20,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Pidgeot": {
      "SnipeIV": 80,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 1,
      "AutoSnipeCandy": 900,
      "Level": 20,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
```

### (OPTIONAL) Your Log:
```
[02:55:11] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 27 CP: (763/1086) IV: 56.00% | Chance: 22.75% | 9095983.10m dist | with a UltraBall (51 left). | 160 EXP earned | Candies: 169 | lat: 45.534327 long: 10.224790 | Move1: SteelWingFast Move2: Twister | Rarity: Common | Capture Reason: Default | Sex: Male
[02:55:22] (SNIPER) (InternalSnipe) Sniping a Pidgey with 80 IV at 34.0195251300575,-118.289067546402...
[02:55:32] (INFO) (CATCH LIMIT) 529/800
[02:55:32] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 21 CP: (331/581) IV: 80.00% | Chance: 49.46% | 9691724.63m dist | with a GreatBall (70 left). | 170 EXP earned | Candies: 172 | lat: 34.019525 long: -118.289068 | Move1: TackleFast Move2: AerialAce | Rarity: VeryCommon | Capture Reason: Default | Sex: Female
[02:55:40] (SNIPER) (InternalSnipe) Sniping a Togetic with 100 IV at 37.2809776069595,-80.0296079044138...
[02:55:42] (INFO) Skipped Togetic
[02:55:42] (INFO) Filter catch not met. Togetic IV 100 lv 30 1323 move1 HiddenPowerFast move 2 AerialAce
[02:55:42] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 46.67 IV at 45.3678867073291,9.67952611324938...
[02:55:52] (INFO) (CATCH LIMIT) 530/800
[02:55:52] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 12 CP: (328/1086) IV: 47.00% | Chance: 33.59% | 9139672.33m dist | with a GreatBall (69 left). | 170 EXP earned | Candies: 177 | lat: 45.367887 long: 9.679526 | Move1: WingAttackFast Move2: Twister | Rarity: Common | Capture Reason: Default | Sex: Female
[02:56:02] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 60 IV at 40.7865546211138,-73.9792839319255...
[02:56:12] (PKMN) (CatchEscape) | (Normal) Pidgeotto Lvl: 30 CP: (865/1086) IV: 60.00% | Chance: 21.61% | 11280940.11m dist | with a UltraBall (50 left). | lat: 40.786555 long: -73.979284 | Move1: SteelWingFast Move2: AerialAce | Rarity :Common
[02:56:24] (PKMN) (CatchMissed Attempt #2) | (Normal) Pidgeotto Lvl: 30 CP: (865/1086) IV: 60.00% | Chance: 21.61% | 11280940.11m dist | with a UltraBall (49 left). | lat: 40.786555 long: -73.979284 | Move1: SteelWingFast Move2: AerialAce | Rarity :Common
[02:56:27] (PKMN) (CatchMissed Attempt #3) | (Normal) Pidgeotto Lvl: 30 CP: (865/1086) IV: 60.00% | Chance: 21.61% | 11280940.11m dist | with a UltraBall (48 left). | lat: 40.786555 long: -73.979284 | Move1: SteelWingFast Move2: AerialAce | Rarity :Common
[02:56:31] (INFO) (CATCH LIMIT) 531/800
[02:56:31] (PKMN) (CatchSuccess Attempt #4) | (Normal) Pidgeotto Lvl: 30 CP: (865/1086) IV: 60.00% | Chance: 21.61% | 11280940.11m dist | with a UltraBall (47 left). | 210 EXP earned | Candies: 182 | lat: 40.786555 long: -73.979284 | Move1: SteelWingFast Move2: AerialAce | Rarity: Common | Capture Reason: ElementalBadge | Sex: Male
[02:56:41] (SNIPER) (InternalSnipe) Sniping a Pidgey with 80 IV at 48.2195191102826,16.4798058808267...
[02:56:53] (INFO) (CATCH LIMIT) 532/800
[02:56:53] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 11 CP: (172/581) IV: 80.00% | Chance: 66.03% | 8540931.68m dist | with a PokeBall (37 left). | 210 EXP earned | Candies: 185 | lat: 48.219519 long: 16.479806 | Move1: QuickAttackFast Move2: Twister | Rarity: VeryCommon | Capture Reason: Default | Sex: Male
[02:57:11] (SNIPER) (InternalSnipe) Sniping a Pidgey with 84.44 IV at 40.4499285409045,-79.9870624973477...
[02:57:21] (PKMN) (CatchMissed) | (Normal) Pidgey Lvl: 29 CP: (460/581) IV: 84.00% | Chance: 42.6% | 11137319.57m dist | with a GreatBall (68 left). | lat: 40.449929 long: -79.987062 | Move1: QuickAttackFast Move2: AerialAce | Rarity :VeryCommon
[02:57:24] (INFO) (CATCH LIMIT) 533/800
[02:57:24] (PKMN) (CatchSuccess Attempt #2) | (Normal) Pidgey Lvl: 29 CP: (460/581) IV: 84.00% | Chance: 42.6% | 11137319.57m dist | with a GreatBall (67 left). | 120 EXP earned | Candies: 188 | lat: 40.449929 long: -79.987062 | Move1: QuickAttackFast Move2: AerialAce | Rarity: VeryCommon | Capture Reason: Default | Sex: Male
[02:57:33] (SNIPER) (InternalSnipe) Sniping a Pidgey with 91.11 IV at 40.7731908456902,-73.9775391898808...
[02:57:44] (INFO) (CATCH LIMIT) 534/800
[02:57:44] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 2 CP: (25/581) IV: 91.00% | Chance: 100% | 11282475.82m dist | with a PokeBall (38 left). | 210 EXP earned | Candies: 191 | lat: 40.773191 long: -73.977539 | Move1: QuickAttackFast Move2: Twister | Rarity: VeryCommon | Capture Reason: Default | Sex: Female
[02:57:54] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 75.56 IV at 52.2620710599452,10.5303863464021...
[02:58:04] (PKMN) (CatchMissed) | (Normal) Pidgeotto Lvl: 22 CP: (644/1086) IV: 76.00% | Chance: 25.12% | 8573062.52m dist | with a UltraBall (46 left). | lat: 52.262071 long: 10.530386 | Move1: SteelWingFast Move2: Twister | Rarity :Common
[02:58:08] (PKMN) (CatchEscape Attempt #2) | (Normal) Pidgeotto Lvl: 22 CP: (644/1086) IV: 76.00% | Chance: 25.12% | 8573062.52m dist | with a UltraBall (45 left). | lat: 52.262071 long: 10.530386 | Move1: SteelWingFast Move2: Twister | Rarity :Common
[02:58:19] (PKMN) (CatchEscape Attempt #3) | (Normal) Pidgeotto Lvl: 22 CP: (644/1086) IV: 76.00% | Chance: 25.12% | 8573062.52m dist | with a UltraBall (44 left). | lat: 52.262071 long: 10.530386 | Move1: SteelWingFast Move2: Twister | Rarity :Common
[02:58:30] (INFO) (CATCH LIMIT) 535/800
[02:58:30] (PKMN) (CatchSuccess Attempt #4) | (Normal) Pidgeotto Lvl: 22 CP: (644/1086) IV: 76.00% | Chance: 25.12% | 8573062.52m dist | with a UltraBall (43 left). | 120 EXP earned | Candies: 196 | lat: 52.262071 long: 10.530386 | Move1: SteelWingFast Move2: Twister | Rarity: Common | Capture Reason: ElementalBadge | Sex: Female
[02:58:49] (INFO) Traveling to Pokestop: Big Stone (79 m) (5 seconds) (route NecroBot Walk)
[02:58:51] (SNIPER) (InternalSnipe) Sniping a Pidgey with 84.44 IV at 37.5728371442436,-122.013195226565...
[02:59:02] (INFO) (CATCH LIMIT) 536/800
[02:59:02] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 12 CP: (189/581) IV: 84.00% | Chance: 63.58% | 9179694.59m dist | with a PokeBall (42 left). | 210 EXP earned | Candies: 199 | lat: 37.572837 long: -122.013195 | Move1: QuickAttackFast Move2: AirCutter | Rarity: VeryCommon | Capture Reason: Default | Sex: Female
[02:59:10] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 64.44 IV at 44.976812983951,-93.2369051774625...
[02:59:21] (INFO) (CATCH LIMIT) 537/800
[02:59:21] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 12 CP: (346/1086) IV: 64.00% | Chance: 33.59% | 10187847.10m dist | with a GreatBall (68 left). | 170 EXP earned | Candies: 204 | lat: 44.976813 long: -93.236905 | Move1: WingAttackFast Move2: AirCutter | Rarity: Common | Capture Reason: Default | Sex: Female
[02:59:29] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 48.89 IV at 40.7033562729723,-74.4086387076069...
[02:59:37] (INFO) (CATCH LIMIT) 538/800
[02:59:37] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 22 CP: (620/1086) IV: 49.00% | Chance: 25.12% | 11278396.79m dist | with a UltraBall (42 left). | 210 EXP earned | Candies: 209 | lat: 40.703356 long: -74.408639 | Move1: SteelWingFast Move2: AirCutter | Rarity: Common | Capture Reason: Default | Sex: Female
[02:59:46] (SNIPER) (InternalSnipe) Sniping a Pidgey with 82.22 IV at 45.4632784518134,9.19543261746326...
[02:59:56] (PKMN) (CatchMissed) | (Normal) Pidgey Lvl: 5 CP: (74/581) IV: 82.00% | Chance: 92.33% | 9159811.83m dist | with a PokeBall (41 left). | lat: 45.463278 long: 9.195433 | Move1: QuickAttackFast Move2: AerialAce | Rarity :VeryCommon
[03:00:00] (INFO) (CATCH LIMIT) 539/800
[03:00:00] (PKMN) (CatchSuccess Attempt #2) | (Normal) Pidgey Lvl: 5 CP: (74/581) IV: 82.00% | Chance: 92.33% | 9159811.83m dist | with a PokeBall (40 left). | 110 EXP earned | Candies: 212 | lat: 45.463278 long: 9.195433 | Move1: QuickAttackFast Move2: AerialAce | Rarity: VeryCommon | Capture Reason: Default | Sex: Male
[03:00:10] (POKESTOP) Name: Big Stone XP: 50, Gems: 0, Items: 3 x ItemPokeBall, Lat: 35.188075, Long: 128.078074, Alt: 40.3830430567186
[03:00:10] (INFO) (POKESTOP LIMIT) 874/1500
[03:00:11] (INFO) Traveling to Pokestop: Pedestal Near Jinju Museum (103 m) (6 seconds) (route NecroBot Walk)
[03:00:19] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 53.33 IV at 41.3876992064944,2.17177356940689...
[03:00:29] (PKMN) (CatchFlee) | (Normal) Pidgeotto Lvl: 27 CP: (759/1086) IV: 53.00% | Chance: 22.75% | 9879622.86m dist | with a UltraBall (41 left). | lat: 41.387699 long: 2.171774 | Move1: WingAttackFast Move2: AirCutter | Rarity :Common
[03:00:32] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 31.11 IV at 37.4970465629473,127.029424381424...
[03:00:42] (INFO) (CATCH LIMIT) 540/800
[03:00:42] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 26 CP: (677/1086) IV: 31.00% | Chance: 23.17% | 273543.06m dist | with a UltraBall (40 left). | 210 EXP earned | Candies: 217 | lat: 37.497047 long: 127.029424 | Move1: SteelWingFast Move2: AerialAce | Rarity: Common | Capture Reason: Default | Sex: Female
[03:00:53] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 64.44 IV at 52.5248522596348,13.4234115193067...
[03:01:05] (INFO) (CATCH LIMIT) 541/800
[03:01:05] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 6 CP: (161/1086) IV: 64.00% | Chance: 47.33% | 8405494.07m dist | with a GreatBall (67 left). | 170 EXP earned | Candies: 222 | lat: 52.524852 long: 13.423412 | Move1: WingAttackFast Move2: Twister | Rarity: Common | Capture Reason: Default | Sex: Female
[03:01:18] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 93.33 IV at 52.2733269951712,10.5256798636112...
[03:01:28] (PKMN) (CatchMissed) | (Normal) Pidgeotto Lvl: 17 CP: (521/1086) IV: 93.00% | Chance: 28.44% | 8572473.91m dist | with a UltraBall (39 left). | lat: 52.273327 long: 10.525680 | Move1: WingAttackFast Move2: AirCutter | Rarity :Common
[03:01:32] (INFO) (CATCH LIMIT) 542/800
[03:01:32] (PKMN) (CatchSuccess Attempt #2) | (Normal) Pidgeotto Lvl: 17 CP: (521/1086) IV: 93.00% | Chance: 28.44% | 8572473.91m dist | with a UltraBall (38 left). | 160 EXP earned | Candies: 227 | lat: 52.273327 long: 10.525680 | Move1: WingAttackFast Move2: AirCutter | Rarity: Common | Capture Reason: Default | Sex: Female
[03:01:42] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 82.22 IV at 37.742626454004,-25.6746217394545...
[03:01:52] (INFO) (CATCH LIMIT) 543/800
[03:01:52] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 12 CP: (361/1086) IV: 82.00% | Chance: 33.59% | 11475608.45m dist | with a GreatBall (66 left). | 210 EXP earned | Candies: 232 | lat: 37.742626 long: -25.674622 | Move1: SteelWingFast Move2: AerialAce | Rarity: Common | Capture Reason: Default | Sex: Male
[03:02:00] (SNIPER) (InternalSnipe) Sniping a Pidgey with 95.56 IV at 40.2328832118592,-111.665373819398...
[03:02:11] (INFO) (CATCH LIMIT) 544/800
[03:02:11] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 14 CP: (227/581) IV: 96.00% | Chance: 59.4% | 9647183.38m dist | with a PokeBall (42 left). | 210 EXP earned | Candies: 235 | lat: 40.232883 long: -111.665374 | Move1: QuickAttackFast Move2: Twister | Rarity: VeryCommon | Capture Reason: Default | Sex: Male
[03:02:19] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 68.89 IV at 38.7129329072972,-9.13381162047964...
[03:02:29] (INFO) (CATCH LIMIT) 545/800
[03:02:29] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 3 CP: (74/1086) IV: 69.00% | Chance: 67.57% | 10703469.12m dist | with a PokeBall (41 left). | 210 EXP earned | Candies: 240 | lat: 38.712933 long: -9.133812 | Move1: SteelWingFast Move2: Twister | Rarity: Common | Capture Reason: Default | Sex: Male
[03:02:40] (SNIPER) (InternalSnipe) Sniping a Goldeen with 100 IV at -35.0925580398084,138.547918750703...
[03:02:49] (PKMN) (CatchMissed) | (Normal) Goldeen Lvl: 30 CP: (863/1007) IV: 100.00% | Chance: 39.45% | 7896929.17m dist | with a UltraBall (37 left). | lat: -35.092558 long: 138.547919 | Move1: PeckFast Move2: AquaTail | Rarity :VeryCommon
[03:02:52] (INFO) (CATCH LIMIT) 546/800
[03:02:52] (PKMN) (CatchSuccess Attempt #2) | (Normal) Goldeen Lvl: 30 CP: (863/1007) IV: 100.00% | Chance: 39.45% | 7896929.17m dist | with a UltraBall (36 left). | 160 EXP earned | Candies: 15 | lat: -35.092558 long: 138.547919 | Move1: PeckFast Move2: AquaTail | Rarity: VeryCommon | Capture Reason: Default | Sex: Male
[03:03:00] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 48.89 IV at 45.4736420335729,9.20488831977735...
[03:03:10] (PKMN) (CatchMissed) | (Normal) Pidgeotto Lvl: 6 CP: (160/1086) IV: 49.00% | Chance: 47.33% | 9158440.43m dist | with a GreatBall (65 left). | lat: 45.473642 long: 9.204888 | Move1: WingAttackFast Move2: Twister | Rarity :Common
[03:03:14] (INFO) (CATCH LIMIT) 547/800
[03:03:14] (PKMN) (CatchSuccess Attempt #2) | (Normal) Pidgeotto Lvl: 6 CP: (160/1086) IV: 49.00% | Chance: 47.33% | 9158440.43m dist | with a GreatBall (64 left). | 160 EXP earned | Candies: 245 | lat: 45.473642 long: 9.204888 | Move1: WingAttackFast Move2: Twister | Rarity: Common | Capture Reason: Default | Sex: Male
[03:06:45] (INFO) Traveling to Pokestop: Bamboo Grove (257 m) (16 seconds) (route NecroBot Walk)
[03:06:46] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 44.44 IV at 48.8504652444662,2.33954892377657...
[03:06:57] (BERRY) Used Nanab Berry | 0 remaining
[03:06:58] (INFO) (CATCH LIMIT) 548/800
[03:06:58] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 28 CP: (768/1086) IV: 44.00% | Chance: 22.35% | 9250465.89m dist | with a UltraBall (37 left). | 170 EXP earned | Candies: 250 | lat: 48.850465 long: 2.339549 | Move1: SteelWingFast Move2: AirCutter | Rarity: Common | Capture Reason: ElementalBadge | Sex: Female
[03:07:09] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 51.11 IV at 34.0057902425052,-118.474215496813...
[03:07:19] (INFO) (CATCH LIMIT) 549/800
[03:07:19] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 11 CP: (299/1086) IV: 51.00% | Chance: 35% | 9679447.20m dist | with a GreatBall (67 left). | 210 EXP earned | Candies: 255 | lat: 34.005790 long: -118.474215 | Move1: WingAttackFast Move2: AerialAce | Rarity: Common | Capture Reason: Default | Sex: Male
[03:07:32] (SNIPER) (InternalSnipe) Sniping a Pidgey with 91.11 IV at 32.8077404551515,130.711618896802...
[03:07:34] (SERVICE) Pokemon despawned or wrong link format!
[03:07:34] (SNIPER) (InternalSnipe) Sniping a Pidgey with 84.44 IV at -34.927614756191,138.599077867198...
[03:07:44] (INFO) (CATCH LIMIT) 550/800
[03:07:44] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 28 CP: (444/581) IV: 84.00% | Chance: 43.3% | 7879578.69m dist | with a GreatBall (66 left). | 170 EXP earned | Candies: 258 | lat: -34.927615 long: 138.599078 | Move1: QuickAttackFast Move2: AirCutter | Rarity: VeryCommon | Capture Reason: Default | Sex: Female
[03:07:54] (SNIPER) (InternalSnipe) Sniping a Pidgeotto with 51.11 IV at 37.8011781137187,140.925709638164...
[03:08:03] (INFO) (CATCH LIMIT) 551/800
[03:08:03] (PKMN) (CatchSuccess) | (Normal) Pidgeotto Lvl: 12 CP: (337/1086) IV: 51.00% | Chance: 33.59% | 1184061.54m dist | with a GreatBall (65 left). | 210 EXP earned | Candies: 263 | lat: 37.801178 long: 140.925710 | Move1: WingAttackFast Move2: Twister | Rarity: Common | Capture Reason: Default | Sex: Female
[03:08:15] (SNIPER) (InternalSnipe) Sniping a Pidgey with 84.44 IV at 40.7544702060143,-73.9679887425946...
[03:08:28] (INFO) (CATCH LIMIT) 552/800

```
### Other Information
priority of pidgey 5, pidgeot 1, pidgeotto 10
I don't think there are more pigeottoes than pidgey, but even pidgey has lower priority, it catches pidgeotto a lot with priority 10.

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by yayahai** [comment] 2017-03-05 18:35
What's the use asking again samuritroung will again close this thread.

**Comment by hardknoxni69a** [comment] 2017-03-05 22:28
just because a thread is closed doesnt mean u cant respond and sure doesnt mean u open again turn off candy requirements as this may be making the the bot go after pidgeotto a little more because its trying to farm candy

**Closed by hardknoxni69a** 2017-03-05 22:28 UTC

**Comment by yayahai** [comment] 2017-03-06 01:13
I agree . But the situation must be resolved before closing a thread.
Now as you have explained the issue and the cause of problem it's acceptable to close the thread hardknoxni69a.

**Comment by ning1002** [comment] 2017-03-06 08:02
sorry about  reopening, I thought no one cares once it is closed.
anyway, the thing is I don't see the difference of levels of priorities
or I don't understand the mechanism how the priority works...

**Comment by hardknoxni69a** [comment] 2017-03-07 02:53
Issues are like bugs being actively worked on it gets closed because one of the devs are working with you no need to keep an open issue the priority is #1 highest #10 lowest so if u have a dragonite and a pudgy u want dragonite to get called first that's why there is priority

**Comment by hardknoxni69a** [comment] 2017-03-07 02:55
As u see people can still respond and help it just doesn't need a big open issue flag taking away attention from issues that could lead to serious problems once a dev responds we get emailed for all.activity on the thread closed or not don't worry we aren't forgetting about you

**Comment by ning1002** [comment] 2017-03-07 21:09
yap, i see.
thank you~
